version: '3.3'
services:
  db:
    image: mariadb
    restart: always
    env_file: ./.env
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3309:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./my-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  node:
    build: ./web
    env_file: ./.env
    ports:
      - '3000:3000'
    depends_on:
      - db
    restart: on-failure
# Names our volume
volumes:
  my-db:
